# Data statistics

```{r load_data_stats}
load("data/data.Rdata")
```

## Sequencing reads statistics

```{r reads_stats}
sample_metadata %>% 
    summarise(Total=sum(reads_post_fastp * 150 / 1000000000) %>% round(2), 
              mean=mean(reads_post_fastp * 150 / 1000000000) %>% round(2),
              sd=sd(reads_post_fastp * 150 / 1000000000) %>% round(2)) %>%
    unite("Average",mean, sd, sep = " ± ", remove = TRUE) %>%
    tt()
```



## DNA fractions
```{r dna_fractions_stats}
sequence_fractions <- read_counts %>%
  pivot_longer(-genome, names_to = "sample", values_to = "value") %>%
  group_by(sample) %>%
  summarise(mags = sum(value)) %>%
	left_join(sample_metadata, by = join_by(sample == sample)) %>%
	select(sample,mags,metagenomic_bases,host_bases,bases_lost_fastp_percent) %>%
	mutate(mags_bases = mags*146) %>%
	mutate(lowqual_bases = ((metagenomic_bases+host_bases)/(1-bases_lost_fastp_percent))-(metagenomic_bases+host_bases)) %>%
	mutate(unmapped_bases = metagenomic_bases - mags_bases) %>%
	mutate(unmapped_bases = ifelse(unmapped_bases < 0, 0, unmapped_bases)) %>%
	select(sample, lowqual_bases, host_bases, unmapped_bases, mags_bases)

sequence_fractions %>%
  mutate_at(vars(-sample), ~./1000000000) %>%
  rename("Sample"=1, "Low quality"=2, "Mapped to host"=3, "Unmapped"=4, "Mapped to MAGs"=5) %>%
  tt()
```


```{r dna_fractions_plot, message=FALSE, warning=FALSE, fig.height=6, fig.width=10, fig.fullwidth=TRUE}
#Fractions of DNA that are low quality, host, unmapped, or mags
sequence_fractions %>%
	pivot_longer(!sample, names_to = "fraction", values_to = "value") %>%
	mutate(value = value / 1000000000) %>%
	mutate(fraction = factor(fraction, levels = c("lowqual_bases","host_bases","unmapped_bases","mags_bases"))) %>%
	ggplot(., aes(x = sample, y = value, fill=fraction)) +
	    geom_bar(position="stack", stat = "identity") +
      scale_fill_manual(name="Sequence type",
                    breaks=c("lowqual_bases","host_bases","unmapped_bases","mags_bases"),
                    labels=c("Low quality","Mapped to host","Unmapped","Mapped to MAGs"),
                    values=c("#CCCCCC", "#bcdee1", "#d8b8a3","#93655c"))+
	    labs(x = "Samples", y = "Amount of data (GB)") +
	    theme_classic() +
	    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size=6),legend.position = "bottom")
```
```{r summary_stats}
#Read Length
#Minimum read length
min_read = min(sequence_fractions$mags_bases)
min_read
min_row = which(match(sample_metadata$sample, sequence_fractions$sample[which(match(sequence_fractions$mags_bases, min(sequence_fractions$mags_bases))==1)])==1)
sample_metadata[min_row,c(1,3,5,7,20)]

#Minimum read length
max_read = max(sequence_fractions$mags_bases)
max_read
max_row = which(match(sample_metadata$sample, sequence_fractions$sample[which(match(sequence_fractions$mags_bases, min(sequence_fractions$mags_bases))==1)])==1)
sample_metadata[min_row,c(1,3,5,7,20)]

#Completeness
#Average
mean(genome_metadata$completeness)
#Standard Deviation
sd(genome_metadata$completeness)

#Contamination
#Average
mean(genome_metadata$contamination)
#Standard Deviation
sd(genome_metadata$contamination)

```
```{r sequencing statistics, warning=FALSE, comments="", message=FALSE}

seq_stats = genome_metadata
read_summary=read_counts_filt
read_summary = read_summary[match(seq_stats$genome, read_summary$genome), ]
read_summary = column_to_rownames(read_summary, var = "genome")

seq_stats$length.megabases. = seq_stats$length * 150/1000000
seq_stats$Total.Reads = rowSums(read_summary)
seq_stats$Total.Basepairs..MB. = seq_stats$Total.Reads * 150/1000000
seq_stats$x.Coverage = seq_stats$Total.Basepairs..MB. / seq_stats$length.megabases.


ggplot(seq_stats, aes(x=x.Coverage)) + geom_histogram(binwidth = 0.2, fill = "skyblue", color = "black") +
  labs(x = "Coverage (binned)", y = "Frequency of MAGs") + 
  scale_x_continuous(limits = c(0, 10)) + 
  scale_y_continuous(limits = c(0, 75)) + 
  geom_vline(xintercept = median(seq_stats$x.Coverage, na.rm = TRUE), linetype = "dashed", color = "red") + 
  theme_minimal()

ggplot(seq_stats, aes(x=Total.Basepairs..MB.)) + geom_histogram(binwidth = 100, fill = "skyblue", color = "black") +
  labs(x = "Basepairs Sequenced (binned)", y = "Frequency of MAGs") + scale_x_continuous(limits = c(0, 3000)) + 
  geom_vline(xintercept = median(seq_stats$Total.Basepairs..MB., na.rm = TRUE), linetype = "dashed", color = "red") + 
  theme_minimal()

ggplot(seq_stats, aes(x=completeness)) + geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  labs(x = "Completeness of MAG (binned) (%)", y = "Frequency of MAGs") + scale_x_continuous(limits = c(0, 100)) + 
  geom_vline(xintercept = median(seq_stats$completeness, na.rm = TRUE), linetype = "dashed", color = "red") + 
  theme_minimal()

ggplot(seq_stats, aes(x=contamination)) + geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
  labs(x = "Contamination of MAG (binned) (%)", y = "Frequency of MAGs") + #scale_x_continuous(limits = c(0, 100)) + 
  geom_vline(xintercept = median(seq_stats$contamination, na.rm = TRUE), linetype = "dashed", color = "red") + 
  theme_minimal()



```

## Recovered microbial fraction

```{r data_estimations_plot, message=FALSE, warning=FALSE, fig.height=6, fig.width=10, fig.fullwidth=TRUE}
#Fraction of DNA that was recovered vs expected separated by species and sample type

singlem_table <- sequence_fractions %>%
	mutate(mags_proportion = round((mags_bases / (mags_bases + unmapped_bases))*100,2)) %>%
	left_join(sample_metadata, by = join_by(sample == sample))  %>%
	mutate(singlem_proportion = round(singlem_fraction*100,2)) %>%
	select(sample,mags_proportion,singlem_proportion) %>%
	mutate(mags_proportion = ifelse(singlem_proportion == 0, 0, mags_proportion)) %>% #convert zeros to NA
	mutate(singlem_proportion = ifelse(singlem_proportion == 0, NA, singlem_proportion)) %>% #convert zeros to NA
	mutate(singlem_proportion = ifelse(singlem_proportion < mags_proportion, NA, singlem_proportion)) %>% #if singlem is smaller, then NA, to simplify plot
	mutate(singlem_proportion = ifelse(singlem_proportion > 100, 100, singlem_proportion)) #simplify

singlem_table %>%
	pivot_longer(!sample, names_to = "proportion", values_to = "value") %>%
	left_join(sample_metadata, by = join_by(sample == sample))  %>%
	mutate(proportion = factor(proportion, levels = c("mags_proportion","singlem_proportion"))) %>%
	ggplot(., aes(x = value, y = sample, color=proportion)) +
			geom_line(aes(group = sample), color = "#f8a538") +
			geom_point() +
      scale_color_manual(name="Proportion",
                    breaks=c("mags_proportion","singlem_proportion"),
                    labels=c("Recovered","Estimated"),
                    values=c("#52e1e8", "#876b53"))+
      facet_nested(species + sample_type ~ ., scales="free",space="free")+
			theme_classic() +
			labs(y = "Samples", x = "Prokaryotic fraction (%)") +
	    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size=6),
	          legend.position = "right",
	          strip.background.y=element_rect(color = NA, fill= "#f4f4f4"))

```