## Functional Differences

### Calculate GIFT Scores
```{r calculate_gift, warning=FALSE}
# Aggregate bundle-level GIFTs into the compound level
GIFTs_elements <- to.elements(genome_gifts, GIFT_db2)
GIFTs_elements_filtered <- GIFTs_elements[rownames(GIFTs_elements) %in% genome_counts$genome, ]
GIFTs_elements_filtered <- as.data.frame(GIFTs_elements_filtered) %>%
  select_if(~ !is.numeric(.) || sum(.) != 0)

elements <- GIFTs_elements_filtered %>%
  as.data.frame()

# Aggregate element-level GIFTs into the function level
GIFTs_functions <- to.functions(GIFTs_elements_filtered, GIFT_db2)
functions <- GIFTs_functions %>%
  as.data.frame()

# Aggregate function-level GIFTs into overall Biosynthesis, Degradation and Structural GIFTs
GIFTs_domains <- to.domains(GIFTs_functions, GIFT_db2)
domains <- GIFTs_domains %>%
  as.data.frame()

# Get community-weighed average GIFTs per sample
GIFTs_elements_community <- to.community(GIFTs_elements_filtered, genome_counts_filt %>% column_to_rownames(., "genome") %>% tss(), GIFT_db2)
GIFTs_functions_community <- to.community(GIFTs_functions, genome_counts_filt %>% column_to_rownames(., "genome") %>% tss(), GIFT_db2)
GIFTs_domains_community <- to.community(GIFTs_domains, genome_counts_filt %>% column_to_rownames(., "genome") %>% tss(), GIFT_db2)

```

### Functional Level
```{r functional_level_gift}
GIFTs_functions_community_no0 <- GIFTs_functions_community[rowSums(GIFTs_functions_community[])>0,]

GIFTs_functions_community_no0 %>%
    as.data.frame() %>%
    rownames_to_column(var="sample") %>%
    pivot_longer(!sample,names_to="trait",values_to="gift") %>%
    left_join(sample_metadata, by = join_by(sample == sample)) %>%
    ggplot(aes(x=trait,y=sample,fill=gift)) +
        geom_tile(colour="white", linewidth=0.2)+
        scale_fill_gradientn(colours=rev(c("#2066a8", "#ededed")))+
        facet_grid(sample_type ~ ., scales="free",space="free")
```





### Element Level
```{r element_level_gift, fig.height=12, fig.width=8, fig.fullwidth=TRUE}
#Filter out samples with only 0 GIFT scores
GIFTs_elements_community_no0 <- GIFTs_elements_community[rowSums(GIFTs_elements_community[])>0,]

GIFTs_elements_community_no0 %>%
    as.data.frame() %>%
    rownames_to_column(var="sample") %>%
    pivot_longer(!sample,names_to="trait",values_to="gift") %>%
    left_join(sample_metadata, by = join_by(sample == sample)) %>%
as.data.frame(GIFTs_elements_community_no0) %>%
    mutate(functionid = substr(trait, 1, 3)) %>% 
    mutate(trait = case_when(
      trait %in% GIFT_db2$Code_element ~ GIFT_db2$Element[match(trait, GIFT_db2$Code_element)],
      TRUE ~ trait
    )) %>%
    mutate(functionid = case_when(
      functionid %in% GIFT_db2$Code_function ~ GIFT_db2$Function[match(functionid, GIFT_db2$Code_function)],
      TRUE ~ functionid
    )) %>%
    mutate(trait=factor(trait,levels=unique(GIFT_db2$Element))) %>%
    mutate(functionid=factor(functionid,levels=unique(GIFT_db2$Function))) %>%
    ggplot(aes(x=sample,y=trait,fill=gift)) +
        geom_tile(colour="white", linewidth=0.2)+
        scale_fill_gradientn(colours=rev(c("#2066a8", "#ededed"))) + 
        #facet_nested(~ species + sample_type,  scales="free", space="free") + 
        facet_grid(functionid ~ sample_type, scales="free",space="free") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
              strip.text.y = element_text(angle = 0), axis.text.y = element_text(angle=45, size=5)) + 
        labs(y="Functional Attribute",x="Samples",fill="GIFT")


```
### GIFT Wilcoxon Comparison (Species)
```{r community_elem_species, comment="", message=FALSE, warning=FALSE, fig.height=6, fig.width=8, fig.fullwidth=TRUE}
element_gift <- GIFTs_elements_community_no0 %>% 
  as.data.frame() %>% 
  rownames_to_column(., "sample") %>% 
  #Change column number to column in sample_metadata to change comparison sample_type, species, etc
  left_join(sample_metadata[c(1,3)], by="sample")
comparison = colnames(element_gift)[length(colnames(element_gift))]

uniqueGIFT_db<- unique(GIFT_db2) %>% unite("Function",Function:Element, sep= "_", remove=FALSE)

#Wilcoxan test
sig_wilcox_species = element_gift %>%
  pivot_longer(-c(sample, comparison), names_to = "trait", values_to = "value") %>%
  group_by(trait) %>%
  summarise(
    p_value = wilcox.test(value ~ get(comparison))$p.value,
    mean_1 = mean(value[get(comparison) == unique(element_gift[,comparison])[1]], na.rm = TRUE),
    mean_2 = mean(value[get(comparison) == unique(element_gift[,comparison])[2]], na.rm = TRUE),
    mean_difference = mean_1 - mean_2,  # Magnitude of difference
    direction = case_when(
      mean_difference > 0 ~ paste("Higher in", unique(element_gift[,comparison])[1]),
      mean_difference < 0 ~ paste("Higher in", unique(element_gift[,comparison])[2]),
      TRUE ~ "No Difference"
    )
  ) %>%
  mutate(trait_name = trait) %>%
  mutate(trait_name = case_when(
      trait %in% GIFT_db2$Code_element ~ GIFT_db2$Element[match(trait_name, GIFT_db2$Code_element)],
      TRUE ~ trait_name
    )) %>%
  mutate(
    p_adjust = p.adjust(p_value, method = "BH"),
    p_label = case_when(
      p_adjust < 0.001 ~ "***",
      p_adjust < 0.01  ~ "**",
      p_adjust < 0.05  ~ "*",
      TRUE ~ ""
    ),
    trait_label = paste0(trait_name, " ", p_label)  # Append p-values to trait name
  )
  
#Match significant functions to table
wilcox_elements_community_no0_sig = GIFTs_elements_community_no0[,which(match(colnames(GIFTs_elements_community_no0), sig_wilcox_species$trait)>0)]

#Create table of gift scores with significant differences between comparisons
heatmap_data <- wilcox_elements_community_no0_sig %>%
    as.data.frame() %>%
    rownames_to_column(var="sample") %>%
    pivot_longer(!sample, names_to="trait", values_to="gift") %>%
    left_join(sample_metadata, by = join_by(sample == sample)) %>%
    mutate(functionid = substr(trait, 1, 3)) %>%
    mutate(trait = case_when(
      trait %in% GIFT_db2$Code_element ~ GIFT_db2$Element[match(trait, GIFT_db2$Code_element)],
      TRUE ~ trait
    )) %>%
    mutate(functionid = case_when(
      functionid %in% GIFT_db2$Code_function ~ GIFT_db2$Function[match(functionid, GIFT_db2$Code_function)],
      TRUE ~ functionid
    )) %>%
    left_join(sig_wilcox_species %>% select(trait, trait_label, mean_difference, direction, p_adjust), by="trait") %>%
    mutate(trait_label = factor(trait_label, levels = unique(trait_label))) %>%
    mutate(functionid = factor(functionid, levels = unique(GIFT_db2$Function)))

ggplot(heatmap_data, aes(x=sample, y=paste0(trait, " ", sig_wilcox_species$p_label), fill=gift)) +  
    geom_tile(colour="white", linewidth=0.2) +  
    scale_fill_gradientn(colours=rev(c("#2066a8", "#ededed"))) +  
    facet_nested(functionid ~ get(comparison) + sample_type, scales="free", space="free") +  
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          strip.text.y = element_text(angle = 0), axis.text.y = element_text(angle=45, size=10)) + 
    labs(y="Functional Attribute (with p-values)", x="Samples", fill="GIFT")

```

### GIFT Wilcoxon Comparison (GI Location)
```{r community_elem_GI, comment="", message=FALSE, warning=FALSE, fig.height=8, fig.width=10, fig.fullwidth=TRUE}
element_gift <- GIFTs_elements_community_no0 %>% 
  as.data.frame() %>% 
  rownames_to_column(., "sample") %>% 
  #Change column number to column in sample_metadata to change comparison sample_type, species, etc
  left_join(sample_metadata[c(1,5)], by="sample")
comparison = colnames(element_gift)[length(colnames(element_gift))]

uniqueGIFT_db<- unique(GIFT_db2) %>% unite("Function",Function:Element, sep= "_", remove=FALSE)

#Wilcoxan test
sig_wilcox_sample = element_gift %>%
  pivot_longer(-c(sample, comparison), names_to = "trait", values_to = "value") %>%
  group_by(trait) %>%
  summarise(
    p_value = wilcox.test(value ~ get(comparison))$p.value,
    mean_1 = mean(value[get(comparison) == unique(element_gift[,comparison])[1]], na.rm = TRUE),
    mean_2 = mean(value[get(comparison) == unique(element_gift[,comparison])[2]], na.rm = TRUE),
    mean_difference = mean_1 - mean_2,  # Magnitude of difference
    direction = case_when(
      mean_difference > 0 ~ paste("Higher in", unique(element_gift[,comparison])[1]),
      mean_difference < 0 ~ paste("Higher in", unique(element_gift[,comparison])[2]),
      TRUE ~ "No Difference"
    )
  ) %>% 
  mutate(trait_name = trait) %>%
  mutate(trait_name = case_when(
      trait %in% GIFT_db2$Code_element ~ GIFT_db2$Element[match(trait_name, GIFT_db2$Code_element)],
      TRUE ~ trait_name
    )) %>%
  mutate(
    p_adjust = p.adjust(p_value, method = "BH"),
    p_label = case_when(
      p_adjust < 0.001 ~ "***",
      p_adjust < 0.01  ~ "**",
      p_adjust < 0.05  ~ "*",
      TRUE ~ ""
    ),
    trait_label = paste0(trait_name, " ", p_label)  # Append p-values to trait name
  )
  

#Match significant functions to table
wilcox_elements_community_no0_sig = GIFTs_elements_community_no0[,which(match(colnames(GIFTs_elements_community_no0), sig_wilcox_sample$trait)>0)]

#Create table of gift scores with significant differences between comparisons
heatmap_data <- wilcox_elements_community_no0_sig %>%
    as.data.frame() %>%
    rownames_to_column(var="sample") %>%
    pivot_longer(!sample, names_to="trait", values_to="gift") %>%
    left_join(sample_metadata, by = join_by(sample == sample)) %>%
    mutate(functionid = substr(trait, 1, 3)) %>%
    mutate(trait = case_when(
      trait %in% GIFT_db2$Code_element ~ GIFT_db2$Element[match(trait, GIFT_db2$Code_element)],
      TRUE ~ trait
    )) %>%
    mutate(functionid = case_when(
      functionid %in% GIFT_db2$Code_function ~ GIFT_db2$Function[match(functionid, GIFT_db2$Code_function)],
      TRUE ~ functionid
    )) %>%
    left_join(sig_wilcox_sample %>% select(trait, trait_label, mean_difference, direction, p_adjust), by="trait") %>%
    mutate(trait_label = factor(trait_label, levels = unique(trait_label))) %>%
    mutate(functionid = factor(functionid, levels = unique(GIFT_db2$Function)))

ggplot(heatmap_data, aes(x=sample, y=paste0(trait, " ", sig_wilcox_sample$p_label), fill=gift)) +  
    geom_tile(colour="white", linewidth=0.2) +  
    scale_fill_gradientn(colours=rev(c("#2066a8", "#ededed"))) +  
    facet_nested(functionid ~ get(comparison) + species, scales="free", space="free") +  
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          strip.text.y = element_text(angle = 0), axis.text.y = element_text(angle=45, size=10)) + 
    labs(y="Functional Attribute (with p-values)", x="Samples", fill="GIFT")

```

## Function Matrix of sample type (Cathartes aura fixed)
```{r Function_Distance_Matrix_caura_sample }
GIFTs_caura = GIFTs_elements_community_no0[which(rownames(GIFTs_elements_community_no0) %in% metadata_caura$sample),]

dist_func = vegdist(GIFTs_caura, method ="bray" )

group_neutral = metadata_caura[na.omit(match(metadata_caura$sample, names(beta_q1n_caura$S))),]

adonis2(dist_func ~ group_neutral$sample_type, 
        data = as.data.frame(GIFTs_caura) %>% arrange(match(group_neutral$sample,labels(beta_q1n_caura$S))), 
        permutations = 999) %>%
        broom::tidy() %>%
        tt()
betadisper(dist_func, group_neutral$sample_type) %>% permutest()

set.seed(123)
nmds_result <- metaMDS(dist_func, k = 2, trymax = 100)
nmds_scores <- as.data.frame(nmds_result$points)

#GIFT ordination by sample type
nmds_scores$Group <- group_neutral$sample_type

x_cen = mean(nmds_scores$MDS1, na.rm = TRUE)
y_cen = mean(nmds_scores$MDS2, na.rm = TRUE)
ggplot(nmds_scores, aes(x = MDS1, y = MDS2, color = Group)) +
  geom_point(size = 4) +
  scale_color_manual(values = sampletype_colors) +
  geom_segment(aes(x = x_cen, y = y_cen, xend = MDS1, yend = MDS2), alpha = 0.9) +
  theme(
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.position = "right", legend.box = "vertical"
    )
```

``` {r Function_Matrix_All_Pairwise}
GIFTs_test = GIFTs_elements_community_no0
metadata_test = sample_metadata

# Metadata variables you want to test
vars <- c("species", "state", "sample_type")

palette_list <- list(
  species = species_colors,
  sample_type = sampletype_colors,
  state = state_colors
)

# Empty lists to hold results
results_adonis <- list()
results_betadisper <- list()

for (var in vars) {
  
  # Other variables to fix
  other_vars <- setdiff(vars, var)
  
  # All combinations of other vars
  combos <- unique(metadata_test[other_vars])
  
  for (i in seq_len(nrow(combos))) {
    combo <- combos[i, , drop = FALSE]
    
    # Subset metadata based on fixed values
    subset_meta <- metadata_test %>%
      filter(across(all_of(other_vars), ~ .x == combo[[cur_column()]]))
    
    # Match GIFT samples to metadata
    subset_gift <- GIFTs_test[rownames(GIFTs_test) %in% subset_meta$sample, ]
    subset_meta <- subset_meta[match(rownames(subset_gift), subset_meta$sample), ]
    
    # Skip if not enough samples
    if (nrow(subset_meta) < 4 || length(unique(subset_meta[[var]])) < 2) next
    
    # Distance matrix
    dist_func <- vegdist(subset_gift, method = "bray")
    
    ## --- Adonis2 ---
    fmla <- as.formula(paste("dist_func ~", var))
    ad <- adonis2(
      fmla,
      data = subset_meta,
      permutations = 999,
      by = "margin"
    )
    ad_df <- broom::tidy(ad) %>%
      mutate(variable = var,
             fixed = paste(paste0(names(combo), "=", combo), collapse = ", "))
    results_adonis[[paste(var, i, sep = "_")]] <- ad_df
    
    ## --- Betadisper ---
    bd <- betadisper(dist_func, subset_meta[[var]])
    bd_perm <- permutest(bd)
    bd_df <- data.frame(
      variable = var,
      fixed = paste(paste0(names(combo), "=", combo), collapse = ", "),
      F_value = bd_perm$tab[1, "F"],
      P_value = bd_perm$tab[1, "Pr(>F)"]
    )
    results_betadisper[[paste(var, i, sep = "_")]] <- bd_df
    
    ## --- NMDS Plot ---
    set.seed(123)
    nmds_result <- metaMDS(dist_func, k = 2, trymax = 100)
    nmds_scores <- as.data.frame(nmds_result$points)
    nmds_scores[[var]] <- subset_meta[[var]]
    
    # Title with wrapping
    title_text <- paste0("GIFTs of ", var, " with ", 
                         paste(paste0(names(combo), "=", combo), collapse = ", "))
    
   # Pick correct palette
palette <- palette_list[[var]]

# Compute centroids per group
centroids <- nmds_scores %>%
  group_by(!!sym(var)) %>%
  summarise(x_cen = mean(MDS1, na.rm = TRUE),
            y_cen = mean(MDS2, na.rm = TRUE))

# Join back with scores
nmds_scores <- nmds_scores %>%
  left_join(centroids, by = var)

p <- ggplot(nmds_scores, aes(x = MDS1, y = MDS2, color = !!sym(var))) +
  geom_point(size = 4) +
  geom_segment(aes(x = x_cen, y = y_cen,
                   xend = MDS1, yend = MDS2),
               alpha = 0.6) +
  scale_color_manual(values = palette) +
  theme(panel.background = element_blank(),) +
  labs(title = str_wrap(title_text, width = 60),
       color = var)
    
fixed_text <- paste(combo, collapse = "_")
filename <- paste0("Figures/SubsettedData/GIFTNMDS/", "GIFTs_", var, "_", fixed_text, ".png")
filename <- gsub(" ", "_", filename)

    ggsave(filename, plot = p, width = 6, height = 5, dpi = 300)    
  }
}

# Bind results
adonis_results <- bind_rows(results_adonis)
betadisper_results <- bind_rows(results_betadisper)

# View results
print(adonis_results)
print(betadisper_results)
```

``` {r GIFT_heatmap_volcano, warning=FALSE}

element_gift <- GIFTs_elements_community_no0 %>% 
  as.data.frame() %>% 
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata[c("sample","sample_type","species","state")], by="sample")

meta_vars <- c("state", "sample_type", "species")
results_list <- list()

palette_list <- list(
  state = state_colors ,
  sample_type = sampletype_colors,
  species = species_colors
)

uniqueGIFT_db<- unique(GIFT_db2) %>% unite("Function",Function:Element, sep= "_", remove=FALSE)

for (var in meta_vars) {
  fixed_vars <- setdiff(meta_vars, var)
  fixed_combos <- element_gift %>%
    distinct(across(all_of(fixed_vars)))
  
  for (i in seq_len(nrow(fixed_combos))) {
    combo <- fixed_combos[i, ]
    subset_df <- element_gift %>%
      filter(across(all_of(fixed_vars), ~ .x == combo[[cur_column()]]))
    
    if (length(unique(subset_df[[var]])) < 2) next
    
    sig_wilcox <- subset_df %>%
      pivot_longer(-c(sample, all_of(meta_vars)), names_to = "trait", values_to = "value") %>%
      group_by(trait) %>%
      summarise(
        p_value = tryCatch(
          wilcox.test(value ~ get(var))$p.value,
          error = function(e) NA_real_
        ),
        mean_1 = mean(value[get(var) == unique(subset_df[[var]])[1]], na.rm = TRUE),
        mean_2 = mean(value[get(var) == unique(subset_df[[var]])[2]], na.rm = TRUE),
        mean_difference = mean_1 - mean_2,
        direction = case_when(
          mean_difference > 0 ~ paste("Higher in", unique(subset_df[[var]])[1]),
          mean_difference < 0 ~ paste("Higher in", unique(subset_df[[var]])[2]),
          TRUE ~ "No Difference"
        ),
        .groups = "drop"
      ) %>%
      mutate(
        p_adjust = p.adjust(p_value, method = "BH"),
        fixed_species = combo$species,
        fixed_state = combo$state,
        fixed_sample_type = combo$sample_type,
        tested_variable = var
      ) %>%
      filter(!is.na(p_value))
    
    if (nrow(sig_wilcox) == 0) next
    sig_wilcox <- sig_wilcox %>%
      mutate(p_label = case_when(
        p_adjust < 0.001 ~ "***",
        p_adjust < 0.01  ~ "**",
        p_adjust < 0.05  ~ "*",
        TRUE ~ ""
      )) %>%
      mutate(trait_label = paste0(trait, " ", p_label))
    
    sig_wilcox <- sig_wilcox %>%
    mutate(negLogP = -log10(p_adjust))
    
    sig_wilcox$Element = sub(".*?_", "", uniqueGIFT_db$Function[match(sig_wilcox$trait, uniqueGIFT_db$Code_element)])
    sig_wilcox$Domain = sub("_.*", "", uniqueGIFT_db$Function[match(sig_wilcox$trait, uniqueGIFT_db$Code_element)])

    
    results_list[[paste(var, combo$species, combo$state, combo$sample_type, sep = "_")]] <- sig_wilcox
    
    #Heatmap
    heatmap_data <- subset_df %>%
      select(sample, all_of(var), all_of(fixed_vars), all_of(sig_wilcox$trait)) %>%
      pivot_longer(cols = sig_wilcox$trait, names_to = "trait", values_to = "gift") %>%
      left_join(sig_wilcox %>% select(trait, trait_label, mean_difference, direction, p_adjust, Element, Domain),
                by = "trait")
    
    
    if(sum(heatmap_data$p_adjust <= 0.05) > 1){
      
    heatmap_sig = heatmap_data[heatmap_data$p_adjust <= 0.05,]
    
    heatmap_plot <- ggplot(heatmap_sig, aes(x = sample, y = Element, fill = gift)) +
      geom_tile(color = "white", linewidth = 0.2) +
      scale_fill_gradientn(colours = rev(c("#2066a8", "#ededed"))) +
      facet_nested(~ get(var), scales = "free", space = "free") +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
            strip.text.y = element_text(angle = 0),
            axis.text.y = element_text(angle = 45, size = 10)) +
      labs(y = "Functional Attribute (with p-values)", x = "Samples", fill = "GIFT") +
      ggtitle(paste("Wilcoxon Test:", var, 
                    "Fixed:",
                    paste(combo[fixed_vars], collapse = ", ")))
    
    ggsave(paste0("Figures/SubsettedData/GIFTHeatmap/", var,
                         "_Fix_", combo$species,
                         combo$state,"_",
                         combo$sample_type, ".png"),
           plot = heatmap_plot,
           width = 10, height = 8, dpi = 300)
    }
    
    #Volcano Plot
    
    if(sum(sig_wilcox$p_adjust <= 0.05) > 1){
      
    sig_sig_wilcox = sig_wilcox[sig_wilcox$p_adjust <= 0.05,]
    
    volcano_plot <- ggplot(sig_sig_wilcox, aes(x = mean_difference, y = negLogP)) +
    geom_point(aes(color = Domain), alpha = 0.7, size = 2) +
    geom_text_repel(aes(label = Element), size = 3, max.overlaps = 10) +
    theme_minimal() +
    theme(
      panel.background = element_rect(fill = "white", color = NA),
      plot.background = element_rect(fill = "white", color = NA)
    ) +
    labs(
      title = paste("Volcano Plot:", var, "Fixed:", paste(combo[fixed_vars], collapse = ", ")),
      x = "GIFT Difference",
      y = "-Log10(Adjusted P-value)",
      color = "Funcational Domain"
    ) +
    scale_color_brewer(palette = "Set2") +
    theme(plot.title = element_text(hjust = 0.5))
  
    # Save volcano plot
    ggsave(paste0("Figures/SubsettedData/Volcano/", "volcano_", var, "_fixed_", paste(combo[fixed_vars], collapse = ", "), ".png"), plot = volcano_plot, width = 8, height = 6, dpi = 300)
    
    }
  }
}

# Optionally, combine all results into one table
all_results <- bind_rows(results_list, .id = "comparison_id")




```
